### ISSUE TITLE
Selfhosting

### ISSUE THREAD

**Issue by bloodieee** [LorittaBot/Loritta#2654]
Wheres the selfhosting.md also please make it selfhostable without docker

**Comment by MrPowerGamerBR** [comment]
We don't support selfhosting Loritta.

If you have the know how, you can figure out how to selfhost her. Just clone the repository, open the project in IDEA and run `LorittaLauncher` in IDEA, then you need to fill out the config file.

And running it with Docker is easier for us because we deploy Loritta with Docker, there's no real reason for us to support non-Docker environments.

**Comment by bloodieee** [comment]
> We don't support selfhosting Loritta.
> 
> If you have the know how, you can figure out how to selfhost her. Just clone the repository, open the project in IDEA and run `LorittaLauncher` in IDEA, then you need to fill out the config file.
> 
> And running it with Docker is easier for us because we deploy Loritta with Docker, there's no real reason for us to support non-Docker environments.

Do it support windows?
